### ISSUE TITLE
CV2

### ISSUE THREAD

**Issue by DolanDack** [yhenon/keras-frcnn#10]
Hi, how do I download cv2 on OSX? I found this framework online but I am not sure if this is the one you refer to https://libraries.io/pypi/cv2. Even if I try to use its pip address `pip install cv2==1.0` I get an error:

```
Could not find a version that satisfies the requirement cv2==1.0 (from versions: )
No matching distribution found for cv2==1.0
```
The same happens even if I simply use `pip install cv2`. There's also OpenCV 3.0 if you mean that framework. Thanks.

**Comment by Timonzimm** [comment]
Check issue #7 , I personaly installed `python-opencv` and it worked ;)
