### ISSUE TITLE
Exceptions

### ISSUE THREAD

**Issue by leifsyliongka** [yhenon/keras-frcnn#101]
Is it expected that I should get the ff. exception messages while running the train script?
Exception: need more than 3 values to unpack
Exception: a must be non-empty

**Setup**
---
Python = 2.7.13
TF version = 1.2.1

**Comment by leifsyliongka** [comment]
It seems like the ```Exception: need more than 3 values to unpack``` is caused by line 

> X2, Y1, Y2, IouS = roi_helpers.calc_iou(R, img_data, C, class_mapping)

 of the training script. Is the IouS variable needed? I seems it's not use anywhere in the script.

**Comment by jahdiel** [comment]
I deleted the IouS, since it appear it was for debugging purposes. I trained and everything seems to be working fine. So my advice is to delete it.

**Comment by leifsyliongka** [comment]
ok, everything seems after removing the IouS. Thank you.
