### ISSUE TITLE
code not working on gpu

### ISSUE THREAD

**Issue by kirk86** [yhenon/keras-frcnn#11]
Hi, may I ask if this code works on gpu? I've tested it and so far I wasn't able to make it work, the tf pool allocator takes for ever and never stops so actually training doesn't start at all.

**Comment by yhenon** [comment]
Sorry I never had time to look into this - it works fine on GPU. An update has been pushed that should help things.

**Comment by kirk86** [comment]
@yhenon thanks, I haven't tested but I'm closing this issue for the moment since you mention that it should be working fine.
