### ISSUE TITLE
Why epoch_length is set to 1000?

### ISSUE THREAD

**Issue by shuuchen** [yhenon/keras-frcnn#113]
not the number of provided training images ?

**Comment by DanMossa** [comment]
I was wondering the same thing. Did you figure out an answer?

**Comment by yhenon** [comment]
This was a fairly arbitrary decision - given the slow speed of training setting `epoch_length == num_image` can be quite slow for larger datasets.

**Comment by shuuchen** [comment]
So what does 1000 mean? 
Randomly choose 1000 images from datasets for training or something else?

**Comment by DanMossa** [comment]
@yhenon Oh that's fair! But what if the num of images ia less than 1000? So should I set to whatever is less? Or just chill with 1000 images?
