### ISSUE TITLE
Randomly get Exception for Value Unpacking

### ISSUE THREAD

**Issue by DanMossa** [yhenon/keras-frcnn#119]
Throughout training, I randomly get the errors

`Exception: not enough values to unpack (expected 4, got 3)`

 But sometimes it goes for like 30 epochs without saying any errors so I'm just not sure

I'm using python 3.5. I think this has something to do with `config.py` but I'm not sure.

The sizes of all the images I'm training on are 784x511

This is the command I'm using

`python train_frcnn.py -o simple -p simpleList.txt --num_epochs 15`

and this is the top portion of my `config.py`

```
		# anchor box scales
		self.anchor_box_scales = [128, 256, 512]

		# anchor box ratios
		self.anchor_box_ratios = [[1, 1], [1, 2], [2, 1]]

		# size to resize the smallest side of the image
		self.im_size = 600
```

Any ideas?

**Comment by ftiguidou** [comment]
Hello,

I believe (maybe someone can correct me if I'm wrong) that this is from the line in train_frcnn.py : 
`			X2, Y1, Y2, IoUs = roi_helpers.calc_iou(R, img_data, C, class_mapping)
`
In the calc_iou function there's a test returning None, None, None if no ROI can be extracted (which leads to the "random" happening of it). You can change this line to None, None, None, None or just remove the IoUs variable in train_frcnn. I think I've read it was for debugging so there's no incidence on the running process.

Hope it helped

**Comment by yhenon** [comment]
This was a bug I recently introduced - I made the function return `IoUs`, as part of future plans. But the function can return early, and in that case it was returning less values, causing the exception. It's been fixed, thanks for reporting this.
