### ISSUE TITLE
Unable to set path 

### ISSUE THREAD

**Issue by SemabAli** [yhenon/keras-frcnn#126]
parser.add_option("-p", "--path", dest="/VOCdevkit/", help="Path to training data.")
parser.add_option("-o", "--parser", dest="parser", help="Parser to use. One of simple or pascal_voc",
				default="pascal_voc")

This gives error

in dest i gave Pascal voc dataset path which had named "VOCdevkit"   .....  i am doing something wrong please help

i didnot understand where to give path of pascal voc dataset and also the format ....  Please help me

**Comment by SemabAli** [comment]
@Ajk4    @yhenon    @ahmedbaracat   @NathanYee

**Comment by shuuchen** [comment]
So what is the error message?

**Comment by SemabAli** [comment]
if not options.train_path:   # if filename is not given
AttributeError: 'Values' object has no attribute 'train_path'

**Comment by shuuchen** [comment]
What is the command line you used?

**Comment by SemabAli** [comment]
i did not use command line .....  It is necessary to use command line to provide path ?

**Comment by SemabAli** [comment]
Thanks @shuuchen  i solved this
