### ISSUE TITLE
[Errno 2] No such file or directory: '\\VOCdevkit\\VOC2007\\ImageSets\\Main\\trainval.txt'

### ISSUE THREAD

**Issue by SemabAli** [yhenon/keras-frcnn#127]
I check file is present .... why this showed to me ....  and also others are 👍 
  
[Errno 2] No such file or directory: '\\VOCdevkit\\VOC2007\\ImageSets\\Main\\trainval.txt'
  File "C:/Users/Semab Ali/Downloads/keras-frcnn-master/train_frcnn.py", line 79, in <module>

[Errno 2] No such file or directory: '\\VOCdevkit\\VOC2007\\ImageSets\\Main\\test.txt'
    all_imgs, classes_count, class_mapping = get_data(options.train_path)
  File "C:\Users\Semab Ali\Downloads\keras-frcnn-master\keras_frcnn\pascal_voc_parser.py", line 46, in get_data

    annots = [os.path.join(annot_path, s) for s in os.listdir(annot_path)]
FileNotFoundError: [WinError 3] The system cannot find the path specified: '\\VOCdevkit\\VOC2007\\Annotations'

**Comment by SemabAli** [comment]
@yhenon @Ajk4  @NathanYee  @kevinkit

**Comment by xuewenyuan** [comment]
try to replace the relative path with absolute path. If that works, it is a problem about path

**Comment by DOsinga** [comment]
Are you sure you have the 2007 set? I just saw a similar error, but it turned out that is because I only have the 2012 set. The instructions only mention that, but the code does seem to require both years.

**Comment by shuuchen** [comment]
@SemabAli 
You can modify the code to have either voc2007 or voc2012 if you only have one dataset.
The are both in voc data format, so make sure the format is correct before test.
Just follow the processing in debug mode to see which files are missing.

**Comment by SemabAli** [comment]
@shuuchen  it worked by changing relative path to absolute path  ....  one more thing can i made this to detect objects in videos ....?

**Comment by shuuchen** [comment]
@SemabAli 
Just use opencv to convert your videos to images.
The trained model can be downloaded from
https://github.com/yhenon/keras-frcnn/issues/23#issuecomment-299265366

**Comment by SemabAli** [comment]
@shuuchen     i want to train using simple parser
C:\Users\Semab Ali\Desktop\DATASET PREPARATION\image000002.jpg, 201, 118, 233 ,138 , car
C:\Users\Semab Ali\Desktop\DATASET PREPARATION\image000003.jpg, 413, 251, 475 ,319 , car
C:\Users\Semab Ali\Desktop\DATASET PREPARATION\image000003.jpg, 110, 133, 156 , 159, car   

this gave me error      "ValueError: not enough values to unpack (expected 6, got 5)"


but  this runs without errors  
C:\Users\Semab Ali\Desktop\DATASET PREPARATION\image000002.jpg, 201, 118, 233 ,138 , car
C:\Users\Semab Ali\Desktop\DATASET PREPARATION\image000003.jpg, 413, 251, 475 ,319 , car

i didnot understand the reason
