### ISSUE TITLE
Input to classifer

### ISSUE THREAD

**Issue by preddy5** [yhenon/keras-frcnn#13]
Hey @yhenon,
Awesome work on the repo.

Correct me if I am wrong, shouldnt input to classifer here(https://github.com/yhenon/keras-frcnn/blob/master/train_frcnn.py#L71) be output from rpn?

Thank You,
Pradyumna.

**Comment by yhenon** [comment]
Hi,
Sorry I took so long - the input to the classifier is indeed the output from RPN. But we want to propagate the gradient through all the layers of the network when training the classifier, so we pass the image and calculate the whole thing.
