### ISSUE TITLE
scaling the stdev

### ISSUE THREAD

**Issue by USTClj** [yhenon/keras-frcnn#134]
**1.  What's the function of stdev ?**
Does anyone know  this which is not found in original py-faster rcnn project ?

in config.py   line 37        
       # scaling the stdev
        self.std_scaling = 4.0
        self.classifier_regr_std = [8.0, 8.0, 4.0, 4.0]

and in roi_helpers.py  line 230
def rpn_to_roi(rpn_layer, regr_layer, C, dim_ordering, use_regr=True, max_boxes=300, overlap_thresh=0.9):
    regr_layer = regr_layer / C.std_scaling

**2.  The function of num_rois**
        # number of ROIs at once
        self.num_rois = 4       I think is the number of sample from each image if I'm correct

**and in train_frcnn.py 
roi_input = Input(shape=(None, 4))**
what's the input data?   I think is the coordinate information

**Comment by olaff09** [comment]
I had the same question, I cannot find the reason for it

**Comment by USTClj** [comment]
# number of ROIs at once
        self.num_rois = 4

**Comment by Tbarowski** [comment]
I'm pretty confused too.. as far as i understood it you reshape your output vector from being inside [-0.5;0.5] to [-4;4] .. Is this really intended?

**Comment by USTClj** [comment]
@yhenon  Could you give us a hint?

**Comment by olaff09** [comment]
@Tbarowski,
I suppose that making the scale range bigger as you say [-4;4] would increase the differences between pixels, making image features more prevalent, but I'm just assuming stuff.

**Comment by yhenon** [comment]
Yeah the original paper says that they should have zero mean & unit standard deviation. I wasn't 100% sure how to achieve that (in fact it is dataset specific). This was a way to get quite close to that on pascal voc. I suspect it shouldn't make that much difference in practice, but it does alter how much the regression layer is contributing to the loss.
