### ISSUE TITLE
problem with train_frcnn.py

### ISSUE THREAD

**Issue by fbazyari** [yhenon/keras-frcnn#15]
Hello,

I am getting an error when trying to use the training function. Error is raised at line 99 of train_frcnn in function model.fit_generator. Error comes from OpenCV actually and is as follows:

`Starting training 
Epoch 1/100
OpenCV Error: Assertion failed ((inv_scale_x > 0 && inv_scale_y > 0)) in resize, file /home/ubuntu/libraries/opencv/modules/imgproc/src/imgwarp.cpp, line 3487
/home/ubuntu/libraries/opencv/modules/imgproc/src/imgwarp.cpp:3487: error: (-215) (inv_scale_x > 0 && inv_scale_y > 0) in function resize`

I can resize images using opencv directly, so installation of OpenCV should be fine. (I must say I have modified the imgwarp.cpp in source code of OpenCV very slightly to avoid problem with resizing large images, this is a known bug as discussed here http://stackoverflow.com/questions/31996367/opencv-resize-fails-on-large-image-with-error-215-ssize-area-0-in-funct    but that should not be the cause of my problem).

Any ideas what might be causing the problem? Or how I can go about finding the cause?

Thanks a lot for your time and help.

**Comment by yhenon** [comment]
Hi,
Thanks for your report, and slowly for the slow reply. Have you found a resolution?
Unfortunately I haven't seen this before - it looks like the image is being scaled by a negative factor? Could you indicate the size of the image and the target image size (found in `config.py`)?
