### ISSUE TITLE
Confused by rpn defined output layers,should the nums of putput set to 2*num_anchors 

### ISSUE THREAD

**Issue by zxy1016** [yhenon/keras-frcnn#164]
hello,i have read your source code,but i am confused by the rpn function.It defined in the vgg.py or renet.py, the rpn function about x_class in your source code is as follow: 
x_class = Convolution2D(num_anchors, (1, 1), activation='sigmoid', kernel_initializer='uniform', name='rpn_out_class')(x)
but according the thesis said that the rpn class output is 2*num_anchors, i have read the prototxt in py-faster-rcnn :layer {
  name: "rpn_cls_score"
  type: "Convolution"
  bottom: "rpn/output"
  top: "rpn_cls_score"
  param { lr_mult: 1.0 }
  param { lr_mult: 2.0 }
  convolution_param {
    num_output: 18   # 2(bg/fg) * 9(anchors)
    kernel_size: 1 pad: 0 stride: 1
    weight_filler { type: "gaussian" std: 0.01 }
    bias_filler { type: "constant" value: 0 }
  }
}

**Comment by shinstra** [comment]
The rpn_out_class layer is a binary classifier, so it's result can be defined as a single probability with respect to one class [p] instead of two probabilities [p, (1 - p)].

**Comment by yhenon** [comment]
Indeed, @shinstra  is correct. Note that the original py-faster-rcnn implementation does things differently, though.
