### ISSUE TITLE
CorrMM: impossible output shape

### ISSUE THREAD

**Issue by Tuzoff** [yhenon/keras-frcnn#17]
Please help me with this error, what could be the reason?

Starting training
Epoch 1/100
Traceback (most recent call last):
  File "train_frcnn.py", line 113, in <module>
    max_q_size=1, workers=1)
  File "/Users/dmitry/anaconda/envs/keras-fcnn/lib/python2.7/site-packages/keras/legacy/interfaces.py", line 88, in wrapper
    return func(*args, **kwargs)
  File "/Users/dmitry/anaconda/envs/keras-fcnn/lib/python2.7/site-packages/keras/engine/training.py", line 1877, in fit_generator
    class_weight=class_weight)
  File "/Users/dmitry/anaconda/envs/keras-fcnn/lib/python2.7/site-packages/keras/engine/training.py", line 1621, in train_on_batch
    outputs = self.train_function(ins)
  File "/Users/dmitry/anaconda/envs/keras-fcnn/lib/python2.7/site-packages/keras/backend/theano_backend.py", line 1122, in __call__
    return self.function(*inputs)
  File "/Users/dmitry/anaconda/envs/keras-fcnn/lib/python2.7/site-packages/theano/compile/function_module.py", line 898, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/Users/dmitry/anaconda/envs/keras-fcnn/lib/python2.7/site-packages/theano/gof/link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/Users/dmitry/anaconda/envs/keras-fcnn/lib/python2.7/site-packages/theano/compile/function_module.py", line 884, in __call__
    self.fn() if output_subset is None else\
ValueError: CorrMM: impossible output shape
  bottom shape: 2 x 1024 x 7 x 7
  weights shape: 1 x 1 x 512 x 1024
  top shape: 2 x 1 x -504 x -1016

Apply node that caused the error: CorrMM{valid, (1, 1), (1, 1)}(Reshape{4}.0, Subtensor{::, ::, ::int64, ::int64}.0)
Toposort index: 1841
Inputs types: [TensorType(float32, 4D), TensorType(float32, 4D)]
Inputs shapes: [(2, 1024, 7, 7), (1, 1, 512, 1024)]
Inputs strides: [(200704, 4, 28672, 4096), (2097152, 2097152, -4096, -4)]
Inputs values: ['not shown', 'not shown']
Outputs clients: [[Elemwise{Add}[(0, 0)](CorrMM{valid, (1, 1), (1, 1)}.0, InplaceDimShuffle{x,0,x,x}.0)]]

Backtrace when the node is created(use Theano flag traceback.limit=N to make it longer):
  File "train_frcnn.py", line 77, in <module>
    trainable=True)
  File "/Users/dmitry/OneDrive/Tuzoff Folders/MyDocs/Code/dental/keras-frcnn/keras_frcnn/resnet.py", line 234, in classifier
    out = classifier_layers(out_roi_pool, trainable=True)
  File "/Users/dmitry/OneDrive/Tuzoff Folders/MyDocs/Code/dental/keras-frcnn/keras_frcnn/resnet.py", line 212, in classifier_layers
    x = conv_block_td(x, 3, [512, 512, 2048], stage=5, block='a', strides=(1, 1), trainable=trainable)
  File "/Users/dmitry/OneDrive/Tuzoff Folders/MyDocs/Code/dental/keras-frcnn/keras_frcnn/resnet.py", line 147, in conv_block_td
    x = TimeDistributed(Convolution2D(nb_filter1, (1, 1), strides=strides, trainable=trainable, kernel_initializer='normal'), name=conv_name_base + '2a')(input_tensor)
  File "/Users/dmitry/anaconda/envs/keras-fcnn/lib/python2.7/site-packages/keras/engine/topology.py", line 578, in __call__
    output = self.call(inputs, **kwargs)
  File "/Users/dmitry/anaconda/envs/keras-fcnn/lib/python2.7/site-packages/keras/layers/wrappers.py", line 177, in call
    y = self.layer.call(inputs)  # (num_samples * timesteps, ...)
  File "/Users/dmitry/anaconda/envs/keras-fcnn/lib/python2.7/site-packages/keras/layers/convolutional.py", line 164, in call
    dilation_rate=self.dilation_rate)
  File "/Users/dmitry/anaconda/envs/keras-fcnn/lib/python2.7/site-packages/keras/backend/theano_backend.py", line 1769, in conv2d
    filter_dilation=dilation_rate)

HINT: Use the Theano flag ‘exception_verbosity=high' for a debugprint and storage map footprint of this apply node.

**Comment by Tuzoff** [comment]
I had to install newer Keras package than mentioned in requirements.txt because on initializers. Here is the full env:

(keras-fcnn) DTMACBOOK:keras-frcnn dmitry$ pip list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
appnope (0.1.0)
backports-abc (0.5)
backports.shutil-get-terminal-size (1.0.0)
backports.ssl-match-hostname (3.4.0.2)
bleach (1.5.0)
configparser (3.5.0)
cycler (0.10.0)
decorator (4.0.11)
entrypoints (0.2.2)
enum34 (1.1.6)
functools32 (3.2.3.post2)
h5py (2.6.0)
html5lib (0.999)
ipykernel (4.6.1)
ipython (5.3.0)
ipython-autotime (0.1)
ipython-genutils (0.2.0)
ipywidgets (6.0.0)
Jinja2 (2.9.6)
jsonschema (2.5.1)
jupyter (1.0.0)
jupyter-client (5.0.1)
jupyter-console (5.1.0)
jupyter-core (4.3.0)
Keras (2.0.3)
MarkupSafe (0.23)
matplotlib (2.0.0)
mistune (0.7.4)
nbconvert (5.1.1)
nbformat (4.3.0)
notebook (5.0.0)
numpy (1.12.1)
opencv-python (3.2.0.7)
pandas (0.19.2)
pandocfilters (1.4.1)
pathlib2 (2.2.1)
pexpect (4.2.1)
pickleshare (0.7.4)
pip (9.0.1)
prompt-toolkit (1.0.14)
ptyprocess (0.5.1)
Pygments (2.2.0)
pyparsing (2.2.0)
python-dateutil (2.6.0)
pytz (2017.2)
PyYAML (3.12)
pyzmq (16.0.2)
qtconsole (4.3.0)
scandir (1.5)
scipy (0.19.0)
setuptools (27.2.0)
simplegeneric (0.8.1)
singledispatch (3.4.0.3)
six (1.10.0)
subprocess32 (3.2.7)
terminado (0.6)
testpath (0.3)
Theano (0.9.0)
tornado (4.4.2)
tqdm (4.11.2)
traitlets (4.3.2)
wcwidth (0.1.7)
wheel (0.29.0)
widgetsnbextension (2.0.0)

**Comment by Tuzoff** [comment]
No such problem on tf, works well

**Comment by yhenon** [comment]
This:
```
 ValueError: CorrMM: impossible output shape
bottom shape: 2 x 1024 x 7 x 7
weights shape: 1 x 1 x 512 x 1024
top shape: 2 x 1 x -504 x -1016
```

looks like a mix-up with channel orders - let me have a look

**Comment by Tuzoff** [comment]
I had to add to

**Comment by hubeihubei** [comment]
@Tuzoff what is you version of keras .I meet the error :"ImportError: cannot import name initializers ".any idea?

**Comment by Tuzoff** [comment]
Yeah, exactly. I just took the latest. Here is my requirements.txt (excluding tensorflow).

[requirements.txt](https://github.com/yhenon/keras-frcnn/files/934784/requirements.txt)

**Comment by Tuzoff** [comment]
Actually, I had to make some more corrections to get the code work. The problem is that many of the are related to our project, and it will take time to prepare a pr for you with only the relevant modifications.

But if you are interested, you can have a look at my clone: https://github.com/Tuzoff/keras-frcnn.

What we are doing now is trying to make the data pipeline faster, because the GPU is not loaded at all. I’ll have a look at the issues of parallelizing today - it breaks.

**Comment by yhenon** [comment]
FYI, I'm still working on this project, and I'm happy to review and accept
any PRs. There are certainly a number of significant issues outstanding,
including the port to keras 2, threading the generators, improving speed of
the roi pooling layers, etc

On Apr 19, 2017 9:41 AM, "Dmitry Tuzoff" <notifications@github.com> wrote:

Actually, I had to make some more corrections to get the code work. The
problem is that many of the are related to our project, and it will take
time to prepare a pr for you with only the relevant modifications.

But if you are interested, you can have a look at my clone:
https://github.com/Tuzoff/keras-frcnn.

What we are doing now is trying to make the data pipeline faster, because
the GPU is not loaded at all. I’ll have a look at the issues of
parallelizing today - it breaks.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/yhenon/keras-frcnn/issues/17#issuecomment-295274172>,
or mute the thread

**Comment by Tuzoff** [comment]
Can we have a chat? My email: dmitry@tuzoff.com

**Comment by hubeihubei** [comment]
@Tuzoff sure ,my email:TerenceChen1210@gmail.com.I  met some error when use this keras-frcc code

**Comment by Tuzoff** [comment]
Sorry, I was referring to @yhenon

**Comment by yhenon** [comment]
I've pushed commit 0c5caf02550e92e333409685ae9e4a3afc4104aa which should fix theano issues. Make sure you are on keras version on 2.0.3, since there was a bug in `TimeDistributed` in some versions prior.
