### ISSUE TITLE
python 3 support

### ISSUE THREAD

**Issue by HuangBo-Terraloupe** [yhenon/keras-frcnn#170]
It is possible to make some changes and use python 3 to run the code?

**Comment by abrad1212** [comment]
Anything is possible, search "how to migrate Python 2 to 3" or something like that on google

**Comment by HuangBo-Terraloupe** [comment]
can someone point out me, if I want to use python 3, which part of code I need modify?

**Comment by rodrigo2019** [comment]
read all issues from this repo, somewhere have a guy that explains how to do that, it worked for me.
You will need  use the "future" library

**Comment by HuangBo-Terraloupe** [comment]
problem solved.
thanks all

**Comment by HuangBo-Terraloupe** [comment]
Hello,
Now I can run the training for python3, but I change a generator, because I have to.
then I got this error:

Exception: Error when checking model target: data should be a Numpy array, or list/dict of Numpy arrays. Found: (array([[[[ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         ..., 
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],


Someone know what's wrong?

**Comment by HuangBo-Terraloupe** [comment]
And I found something strange,
If we use python3 and python2 to run the same training script, the losses start with different value.
For python2 it looks good, but for python3, the regression_loss of RPN starts with 7, it is relative big.

**Comment by Abhijit-2592** [comment]
The script is already python 3 supported. @yhenon  is yet to update the readme file. One word of caution if you are using vgg as basenet refer #169  this small fix will enable training. If this is not fixed the training freezes without any output.

I am closing this issue

**Comment by yhenon** [comment]
I fixed the vgg issue and updated the readme.

**Comment by HuangBo-Terraloupe** [comment]
So now the generator should also works for python 3,5?

**Comment by Abhijit-2592** [comment]
Yes
