### ISSUE TITLE
No progress after Starting training Epoch 1/10

### ISSUE THREAD

**Issue by Abhijit-2592** [yhenon/keras-frcnn#174]
I am training keras faster RCNN on kitti dataset I configured the text file and used simple parser with VGG net

> 
> Parsing annotation files
> Training images per class:
> {'Car': 28742, 'Cyclist': 1627, 'Pedestrian': 4487, 'bg': 0}
> Num classes (including bg) = 4
> Config has been written to config.pickle, and can be loaded when testing to ensure correct results
> Num train samples 6373
> Num val samples 1108
> loading weights from /root/.keras/models/vgg16_weights_tf_dim_ordering_tf_kernels_notop.h5
> Starting training
> Epoch 1/10

After this I am not getting any output. Its been running for more than 17 hrs and still stuck here.
I am using NVIDIA 1060 6GB GPU. GPU is configured properly and it is running properly when I run a keras classification network but There is no GPU involvement in this case at all
I am using python 3 in ubuntu .

**Comment by rodrigo2019** [comment]
Are you using python 3.5?

**Comment by Abhijit-2592** [comment]
Oh thanks. I will try it and will let you know

**Comment by Abhijit-2592** [comment]
I guess #169 is the problem. Will let you know if it works. And yes i am using python 3.5
