### ISSUE TITLE
Split dataset on train and test

### ISSUE THREAD

**Issue by buliginleo** [yhenon/keras-frcnn#188]
Hello!

I have own dataset for detection one object and splitting this dataset on train and val data. How I can give your script on input own separation on train and val? Thank you.

**Comment by rodrigo2019** [comment]
the parser already does it for you in these lines:

`train_imgs = [s for s in all_imgs if s['imageset'] == 'trainval']
val_imgs = [s for s in all_imgs if s['imageset'] == 'test']`

but if need a specific split of dataset, I think you will need modify the parser code.

**Comment by buliginleo** [comment]
@rodrigo2019 thank you!
