### ISSUE TITLE
Does pretrained model "resnet50_weights_th_dim_ordering_th_kernels.h5" produce acceptable results?

### ISSUE THREAD

**Issue by Daikon-Sun** [yhenon/keras-frcnn#19]
I downloaded the resnet50_weights_th_dim_ordering_th_kernels.h5 pretrained model and trained for a single epoch with a single example, so the program will produce a model_frcnn.hdf5. After that, I tested the model but couldn't get any outcome. All instances will not pass the "np.max(P_cls[0,ii,:]) < 0.5" on line 153 in test_frcnn.py. Is this normal or that something went wrong?

**Comment by Daikon-Sun** [comment]
My keras.json:
{
    "image_dim_ordering": "tf",
    "image_data_format": "channels_last",
    "floatx": "float32",
    "epsilon": 1e-07,
    "backend": "tensorflow"
}

**Comment by yhenon** [comment]
The pretrained model `resnet50_weights_th_dim_ordering_th_kernels.h5` is an image classifier trained on imagenet, not an image detector trained on pascal voc. It does not produce satisfactory results. About 80k iterations of training are required to converge on good results for pascal voc (less for simpler challenges).
