### ISSUE TITLE
Image size problem

### ISSUE THREAD

**Issue by HuangBo-Terraloupe** [yhenon/keras-frcnn#199]
After training I run the test_frcnn, I got some bounding box cross the image boundary.
I set image_size to 500, and anchor size to [128, 256, 500],
I got some bounding box start with -16, or end up with 512?
What is the problem?
I think faster rcnn will remove the region proposal that cross the boundary?

**Comment by yhenon** [comment]
faster-rcnn removes proposals that cross the boundary at train time, not at test time. Sometimes generated proposals cross the border -- feel free to clamp them to the border if it fits your needs.
