### ISSUE TITLE
Get the list of predictions

### ISSUE THREAD

**Issue by xitman47** [yhenon/keras-frcnn#200]
Hello! 

I have a list of images. Is there any option to feed this list of images to frcnn and to get the output txt file with the list of predictions (**file_name, class, class probability, bboxes**)? I have looked through the readme, scripts and issues raised but haven't found the answer. I also tried predicting single image but didn't find any output files. Windows 7, py35, Tensorflow used

Thank you!

**Comment by Abhijit-2592** [comment]
@xitman47  please look at the [test_frcnn.py](https://github.com/Abhijit-2592/keras-frcnn/blob/master/test_frcnn.py) in my repo I have already added return statement with (List_of_images"contains images with bbox overlayed",List_of_dets("contains classes and prob"))
returning bbox coordinates is fairly straight forward in that code

append all the real_x1 ...etc to a list inside the last for loop and return it along with the above 3

**Comment by xitman47** [comment]
Thank you very much! I wonder why it is not done here by default..

**Comment by Abhijit-2592** [comment]
glad it helped
