### ISSUE TITLE
Do you center crop images during preprocessing?

### ISSUE THREAD

**Issue by A-Jacobson** [yhenon/keras-frcnn#204]
It's common practice to do center cropping or random cropping while training networks for classification. Do you do the same with frcnn? I didn't see any crops done in the code. Does that mean we train on "squished" images (images with different aspect ratios)?

**Comment by yhenon** [comment]
there is no cropping, since faster-rcnn can take variable image sizes through the use of ROI pooling layers. Although it is common practice in classification to center crop, it doesnt make much sense for object detection, since you might crop out objects of interest.
