### ISSUE TITLE
the python function sorted

### ISSUE THREAD

**Issue by wanjinchang** [yhenon/keras-frcnn#21]
dear editor,when I run the train_frcnn.py,it raised the error TypeError: unorderable types: dict() < dict() from all_img_data = sorted(all_img_data),can you solved for me? Thank you very much!

**Comment by yhenon** [comment]
Try using python2 instead of python 3. This is a duplicate of issue #20 so I'll go ahead and close it. Please reopen if issues remain.

**Comment by wanjinchang** [comment]
I know,but my environment is bulid on python3.5,the structure of all_img_data = sorted(all_img_data),I cannot understand the effect of this function to all_img_data.Looking forward to your reply,thank you!
