### ISSUE TITLE
Error while using tf.image.resize_images() for ROI pooling

### ISSUE THREAD

**Issue by brijml** [yhenon/keras-frcnn#232]
Did anyone run into this error while using the tf.image.resize_images() for ROI pooling
`InvalidArgumentError (see above for traceback): input image must be of non-zero size
	 [[Node: roi_pooling_conv_1/ResizeBilinear_6 = ResizeBilinear[T=DT_FLOAT, align_corners=false, _device="/job:localhost/replica:0/task:0/cpu:0"](roi_pooling_conv_1/ExpandDims_6, roi_pooling_conv_1/size_6)]]`

I checked if there is any ROI for which the height and width is (0,0), I did nott find any such ROI, I put a check for using only those ROIs where the height and width is greater than (pool_size, pool_size) which does not solve the problem.

**Comment by brijml** [comment]
I was not paying attention towards negative examples(anchors with higher probability of being a background). I got that fixed but now my loss is coming out to be an array of length 5. I suppose the loss should be a scalar. Am I doing something wrong?

**Comment by Mrlonelei** [comment]
@brijml hi i got a same problem, could tell me how you fix this , thx a lot
