### ISSUE TITLE
About the slow test speed

### ISSUE THREAD

**Issue by Yudsuki** [yhenon/keras-frcnn#236]
@yhenon I test the code on the camera and I find that the detection speed is twenty times slower than caffe's py-faster-rcnn. I just change the im_size to 300. What should I do if I want to improve the detection speed.
Sorry,I am just a rookie.Can you help me.
Thanks

**Comment by yhenon** [comment]
This repo is now deprecated. Instead, use https://github.com/fizyr/keras-retinanet. Keras-retinanet is more accurate, has higher quality code and runs faster.
