### ISSUE TITLE
Running on cpu

### ISSUE THREAD

**Issue by minxuancao** [yhenon/keras-frcnn#28]
Hi! I am wondering if I could train with this implementation with a small dataset(1000 300*300 images) with cpu?

**Comment by yhenon** [comment]
Well you can try, although it will be quite a bit slower (about 3secs/iteration). It should be ok with so few iamges though.
You will need to:
- set `im_size` to 300 in config.py
- make sure to adjust the size of the bounding boxes appropriately (default is [128, 256, 512], which is too large for a 300px image). This would depend on the objects in your images but something like [64, 128, 256] is pretty standard.
