### ISSUE TITLE
TensorFlow backend infinite loop

### ISSUE THREAD

**Issue by Ahleroy** [yhenon/keras-frcnn#32]
Hello,
I wanted to use the project with another dataset. However I can only compute on a CPU.
I have dramatically reduced the size of the images in config.py (150px each side) and reduced the bounding boxes as suggested in [here](https://github.com/yhenon/keras-frcnn/issues/28)  to [128, 64, 32] and then to [64, 32, 16].

I have reduced the number of images from 1000 to 6 (even tried with only one) and the program is still on "Epoch 1/100".

I want to say that I use pre-trained weights for the tensorflow background. May the problem comes from here ?

Regards,

**Comment by yhenon** [comment]
Can you confirm if you are on the latest version of the codebase? Issues with inf loops definitely used to happen more before.

**Comment by sholsapp** [comment]
@yhenon can you programmatically protect against that? An infinite loop is really bad. :)

**Comment by Ahleroy** [comment]
@yhenon Indeed my version was not the lastest. Weird since I download the master before the last modification.
Thank you very much.
