### ISSUE TITLE
train on LISA dataset

### ISSUE THREAD

**Issue by kkawtar** [yhenon/keras-frcnn#38]
Can you please tell me how can I train your model on the Lisa dataset to detect traffic signs, I've already prepared the "my_data.txt" but when I try to train the model with -o simple my_data.txt I get an error when model tries to excute the "get_data" function from pascal_voc_parser.
thank you

**Comment by yhenon** [comment]
Are you sure you're on the latest version of the codebase? `python train_frcnn.py -o simple --path simple_data.txt` works just fine for me.

**Comment by kkawtar** [comment]
I didn't notice your note to use python 2, I was using 3 , now it works. do you have any recomendation how I can speed up my cpu ? i'm working with i7 8go

**Comment by yhenon** [comment]
Unfortunately training a large neural network without a GPU is just not that realistic, or you'll have to wait a very long time.

**Comment by kkawtar** [comment]
Thank you sir for your response.
