### ISSUE TITLE
Interested in a more flexible way to pass training data?

### ISSUE THREAD

**Issue by mathetes87** [yhenon/keras-frcnn#48]
@yhenon  I'm looking into using this repo to train a model, but I have very few data so I would need to make more flexible the way the data is fed into your scripts. I need very aggressive data augmentation handled by another library.

Would you be interested to merge this changes into the repo? **I'm thinking about writing the possibility to feed the data with an infinite generator of batches**.

What do you think?

**Comment by yhenon** [comment]
That could potentially be interesting - I'd like to have more augmentation, especially related to scale/rotation. What is the external library you are using?

Note that the current implementation already uses generators that lead to infinite batches.

**Comment by mathetes87** [comment]
That is good to know! Maybe I could help you with the data augmentation part instead. After all, the simple_parser is very simple indeed, I think it could be easily enhanced.

The library is this repo https://github.com/aleju/imgaug, it has worked remarkably well for me.

**Comment by yhenon** [comment]
That looks pretty useful - note that some ops will modify the scale/position of the bounding boxes, so you'd have to also write code to track them through the operations. The color/noise ones would be pretty easy to add.
Have a look at `keras_frcnn/data_augment.py` where all the code related to augmentation lives. It should be reasonably easy to enhance I think.

**Comment by mathetes87** [comment]
I hadn't noticed that the data is fed with generators. Sorry for the previous message...

So I could extend the data_augment file directly as you say. This library I mention already keeps track of the changes to the bounding boxes. I'll take a closer look into all this and propose something before writing any code.

Cheers

**Comment by yhenon** [comment]
Looking forward to it!

**Comment by mathetes87** [comment]
Hi @yhenon, finally I had the time today to integrate the other repo. I have the code working and with the keypoints being adjusted nicely.

I created 2 files, one with parameters to modify and the other with the augmenter calling itself. Being so many parameters, the console-passing-parameters thing would not work so great here.

I am no expert in git, 

1. Should I just make a pull request with the code as it is? Maybe the user should choose between the two augmentation paths with a parameter, I think this is your call. Will you delete the current data_augment file?
2. Lastly, I'm not sure how the other repo should be included.

**Comment by yhenon** [comment]
Hey,
1 - go ahead and make a pull request as is, I can make any further changes that are needed
2 - since it's MIT licensed, we can just pull the parts of the repo we need into this one, and credit it.

**Comment by mathetes87** [comment]
Sent!
