### ISSUE TITLE
Changing rpn_stride

### ISSUE THREAD

**Issue by shahruk10** [yhenon/keras-frcnn#57]
If I change the RPN_stride length from the default of 16, would I have to also change the following line (line #193) in test_frcnn.py and in measure_map.py (line #254)  :

	bboxes[cls_name].append([16*x, 16*y, 16*(x+w), 16*(y+h)])

Are the 16 ought to be replaced by C.rpn_stride ?

**Comment by yhenon** [comment]
Thanks for the report - you are right. I'll fix this in the next commit.
