### ISSUE TITLE
How to rescale image back to original size when testing?

### ISSUE THREAD

**Issue by jahdiel** [yhenon/keras-frcnn#59]
So when I test my model the image is rescaled as one would expect but, the thing is I wish to evaluate the predictions against the ground truth bounding boxes. Meaning that because the image is rescaled when entered into the model the bounding boxes are also rescaled and therefore I can't compare them to the original ground truth because image scale difference. Is there a way to resolve this?

**Comment by yhenon** [comment]
Fixed in bda3feb452a5274471c4d22484de8891a443b4cf, reopen this if there are any issues.
