### ISSUE TITLE
Purpose of sorted(all_img_data)?

### ISSUE THREAD

**Issue by AechPro** [yhenon/keras-frcnn#60]
Hi, I've been spending the last couple of weeks working on re-implementing this project in python 3.6 with a few changes. I've pretty much completed it, but I'm having an issue in the `data_generators.get_anchor_gt()` function. I understand that it is the first line in this function: `all_img_data = sorted(all_img_data)` that causes the error `'<' not supported between instances of 'dict' and 'dict'`. My issue is in re-implementing this. I'm not very familiar with python 2.7, so I'm not sure how it would sort a list of dictionaries. Because of this, I'm not sure how to go about making the equivalent code in python 3.6.

I have two primary questions:
1. Is it actually necessary to sort the image data like this before doing the image processing?
2. What exactly does this function do to the list of dictionaries here?

Any help you can provide would be greatly appreciated.
Thanks!

**Comment by yhenon** [comment]
The sorting is just to provide more reproducible/deterministic results,
it's not important

**Comment by AechPro** [comment]
Alright, thanks for the quick feedback!
