### ISSUE TITLE
train keras-faster RCNN with own Dataset

### ISSUE THREAD

**Issue by akshaylamba** [yhenon/keras-frcnn#63]
I want train keras-faster RCNN with own Dataset..I have 3 Classes which are not present in VOC dataset , It is microscopic Photo of blood smear ...

How Many per classes should I train to get good results..

**Comment by BowieHsu** [comment]
4 classes with default first class is background.

**Comment by yhenon** [comment]
You'll have to try and see, it's very hard to predict these things. 
Pascal voc has about 1 or 2 thousand per class, up to 28000 for the person class. In general some classes are easier than others, and less images can be sufficient.
With medical image data you can typically use lots of data augmentation, you can add horizontal flips, vertical flips, and rotations with `--hf --vf --rot` when training.
