### ISSUE TITLE
Classifier Training Problem

### ISSUE THREAD

**Issue by AechPro** [yhenon/keras-frcnn#68]
Hello, I've found an issue when attempting to run `train_model.py.` 

I am attempting to train as-is with the Pascal VOC 2012 data set. The code seems to go into an infinite recursive loop during training, and never completes a single iteration. I've been able to identify that the problem happens at this line: 
`loss_class = model_classifier.train_on_batch([X, X2[:, sel_samples, :]], [Y1[:, sel_samples, :], Y2[:, sel_samples, :]])` 
but I am not sure why. The code simply pauses and begins to consume a great deal of memory (10GB+). It seems to be that the `train_on_batch` function is recursively looping forever. The reason I believe this to be the case is because if I remove `sys.setrecursionlimit(40000)`  and attempt to train again, it exceeds the system recursion limit and throws a runtime exception. 

I'm doing this in a Python 2.7.3 environment with Keras 2.0.3 and Theano 9.0.

**Comment by AechPro** [comment]
Update: I believe I have confirmed that this is an issue with the version of Theano I am running. I've swapped to the latest version of TensorFlow and the code runs fine.

**Comment by yhenon** [comment]
The theano backend is currently quite poorly supported - tf is just much easier to develop on.
