### ISSUE TITLE
Assertion Error : Arrays are not less ordered during testing

### ISSUE THREAD

**Issue by shahruk10** [yhenon/keras-frcnn#73]
While testing a model I trained with my own dataset, I received the error message below a couple of images in. I changed the non maxima suppression threshold slightly to adjust for my dataset. Could that be the problem ? I am only receiving this error on particular images

/keras_frcnn/roi_helpers.py:138: RuntimeWarning: overflow encountered in exp
  w1 = np.exp(tw) * w

/keras_frcnn/\/roi_helpers.py:265: RuntimeWarning: invalid value encountered in add
  A[2, :, :, curr_layer] += A[0, :, :, curr_layer]

/keras_frcnn/roi_helpers.py:283: RuntimeWarning: invalid value encountered in greater_equal
  idxs = np.where((x1 - x2 >= 0) | (y1 - y2 >= 0))

  File "/test_frcnn.py", line 159, in testModel
    R = roi_helpers.rpn_to_roi(Y1, Y2, C, K.image_dim_ordering(), overlap_thresh=options.non_maxima_suprresion_threshold)

  File "/keras_frcnn/roi_helpers.py", line 288, in rpn_to_roi
    result = non_max_suppression_fast(all_boxes, all_probs, overlap_thresh=overlap_thresh, max_boxes=max_boxes)[0]

  File "/keras_frcnn/roi_helpers.py", line 164, in non_max_suppression_fast
    np.testing.assert_array_less(x1, x2)

  File "/home/shahruk/anaconda2/lib/python2.7/site-packages/numpy/testing/utils.py", line 1051, in assert_array_less
    header='Arrays are not less-ordered')

  File "/home/shahruk/anaconda2/lib/python2.7/site-packages/numpy/testing/utils.py", line 754, in assert_array_compare
    chk_same_position(x_isnan, y_isnan, hasval='nan')

  File "/home/shahruk/anaconda2/lib/python2.7/site-packages/numpy/testing/utils.py", line 735, in chk_same_position
    raise AssertionError(msg)
AssertionError: 
Arrays are not less-ordered

x and y nan location mismatch:
 x: array([  0.,   0.,   1., ...,  42.,  43.,  45.])
 y: array([  2.,   2.,   3., ...,  52.,  52.,  52.])

**Comment by mathetes87** [comment]
This error seems to be exactly as the one I report here: #72 
Note that in my case I didn't touch the maxima suppression threshold

**Comment by shahruk10** [comment]
Also, I got it while testing, but it seems to stem from the non_max_suppression_fast function;

**Comment by yhenon** [comment]
I'm closing this to use #72 as the main issue

**Comment by liuwei16** [comment]
@shahruk10 @yhenon I also got this error and it stems from the non_max_suppression_fast function, because there are nan values in bbox, thus I have modified the non_max_suppression_fast function as follows:
def non_max_suppression_fast(boxes, probs, overlap_thresh=0.9, max_boxes=300):
	# if there are no boxes, return an empty list
	if len(boxes) == 0:
		return [], []
	# judge which box has non value and delete it
	b = np.isnan(boxes)
	c = np.sum(b, axis=1)
	boxes = boxes[c==0,:]

	# grab the coordinates of the bounding boxes
	x1 = boxes[:, 0]
	y1 = boxes[:, 1]
	x2 = boxes[:, 2]
	y2 = boxes[:, 3]

	np.testing.assert_array_less(x1, x2)
	np.testing.assert_array_less(y1, y2)

**Comment by taninaim** [comment]
I got the same error and fixed it by making sure that test_frcnn.py is calling the right config.pickle that was generated when training that particular model_frcnn.hdf5. I trained on multiple computers and each had different configurations (hence different config.pickle).
