### ISSUE TITLE
Problem read input path

### ISSUE THREAD

**Issue by Avrilnon** [yhenon/keras-frcnn#79]
I am trying to use VOC2012 to retrain the model, but always there is the problem of finding the --path correctly, I don't know why but it is really strange, I have the error: cannot find the path, which even doesn't exist in my computer. I used "python3 train_frcnn.py -p /path/of/VOC2012" for compiling.

**Comment by sanjeev-** [comment]
works for me but i realized that i also needed 2007 PAC data which i downloaded here:
http://host.robots.ox.ac.uk/pascal/VOC/voc2007/

i put them both in the same path and it seemed to work for me.  im using ubuntu 16.04, tensor flow 1.0.1 and keras 2.0.2

**Comment by Avrilnon** [comment]
Thanks a lot, I find out that I need to add ' ' to the 'path' then delete the VOC2007 option in pascal_voc_parser.py... I will try your method too, there are some changes between python2 and python3, I have also some exceptions now...

**Comment by sanjeev-** [comment]
yea im using python 2.7 but on linux so there's no tensorflow incompatibility which made it easier.  i assume youre running on windows?

for what it's worth, i find spinning up a separate amazon EC2 instance the easiest way to do this stuff
