### ISSUE TITLE
While launch test.py seems to be not using model_classifier, only model_rpn.

### ISSUE THREAD

**Issue by dmitrysarov** [yhenon/keras-frcnn#88]
is it corresponds to paper?

**Comment by Ahleroy** [comment]
Hello,

Into the test_frcnn.py file, both of the model_classifier and model_rpn are created.
Yet, it seems that it is the model_classifier_only which is used for the classification (but it seems to be exactly the same that the original model_classifier).

One weird thing is that the weights are loaded into the model_classifier (line 107) and not into the model_classifier_only.

I will take a further look later.

Regards

**Comment by dmitrysarov** [comment]
Thank you for answer. 
Could it be that by loading weights for model_classifier
model_classifier.load_weights(C.model_path, by_name=True)
which is model_classifier = Model([feature_map_input, roi_input], classifier)
we load weights for classifier - layers, used in model_classifier_only
model_classifier_only = Model([feature_map_input, roi_input], classifier)?

**Comment by yhenon** [comment]
One is a subset of the other, so we only need to load weights once.
