### ISSUE TITLE
Mask R-CNN

### ISSUE THREAD

**Issue by alexattia** [yhenon/keras-frcnn#95]
It woud be great to implement and include a Keras version of [Mask R-CNN ](https://arxiv.org/pdf/1703.06870.pdf) into this repo. "Mask R-CNN adopts the same two-stage procedure (than Faster R-CNN), with an identical first stage (which is RPN). In the second stage, in parallel to predicting the class and boxoffset, Mask R-CNN also outputs a binary mask for each
RoI. "

**Comment by Ahleroy** [comment]
Hello,

Indeed working on Mask R-CNN would be great. Yet this repository is for faster r-cnn, in my opinion creating a new project would be preferable.

Regards,

**Comment by yhenon** [comment]
Check out here for a very WIP repo with mask frcnn support https://github.com/broadinstitute/keras-rcnn
