### ISSUE TITLE
Tensorboard

### ISSUE THREAD

**Issue by shrishtrived** [yhenon/keras-frcnn#99]
How can I use this implementation to visualize the model in tensorboard ?

**Comment by mathetes87** [comment]
See issue #78. It can be done, but you would need to access either Tensorflow's classes and methods or Tensorboard's Keras callback directly (see [here](https://groups.google.com/forum/#!topic/keras-users/IS-wBskAg0k) for the later)

**Comment by yhenon** [comment]
duplicate of #78 as pointed out by @mathetes87
